version: '3'
services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./monitor/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"

  gotlin:
    build: ./
    image: "gotlin:development"
    depends_on:
      - prometheus
      - grafana
    command:
      - "gotlin"
      - "start"
      - "--http=:9080"
      - "--prometheus"
      - "--pprof"
      - "--executor=false"
    ports:
      - "9080:9080"

  executor:
    build: ./
    image: "gotlin:development"
    depends_on:
      - gotlin
    command:
      - "gotlin"
      - "compute"
      - "--server=gotlin:9527"
    deploy:
      mode: replicated
      replicas: 8
    restart: always

  client:
    build: ./
    image: "gotlin:development"
    depends_on:
      - executor
    command:
      - "gotlin"
      - "start"
      - "--address=:9528"
