// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: gotlin.proto

package gotlin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteStream_Type int32

const (
	ExecuteStream_Unknown ExecuteStream_Type = 0
	ExecuteStream_Connect ExecuteStream_Type = 1
	ExecuteStream_Execute ExecuteStream_Type = 2
	ExecuteStream_Result  ExecuteStream_Type = 3
)

// Enum value maps for ExecuteStream_Type.
var (
	ExecuteStream_Type_name = map[int32]string{
		0: "Unknown",
		1: "Connect",
		2: "Execute",
		3: "Result",
	}
	ExecuteStream_Type_value = map[string]int32{
		"Unknown": 0,
		"Connect": 1,
		"Execute": 2,
		"Result":  3,
	}
)

func (x ExecuteStream_Type) Enum() *ExecuteStream_Type {
	p := new(ExecuteStream_Type)
	*p = x
	return p
}

func (x ExecuteStream_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteStream_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_gotlin_proto_enumTypes[0].Descriptor()
}

func (ExecuteStream_Type) Type() protoreflect.EnumType {
	return &file_gotlin_proto_enumTypes[0]
}

func (x ExecuteStream_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteStream_Type.Descriptor instead.
func (ExecuteStream_Type) EnumDescriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{4, 0}
}

type RegisterExecutorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Labels []*RegisterExecutorRequest_Label `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Host   string                           `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *RegisterExecutorRequest) Reset() {
	*x = RegisterExecutorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExecutorRequest) ProtoMessage() {}

func (x *RegisterExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExecutorRequest.ProtoReflect.Descriptor instead.
func (*RegisterExecutorRequest) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterExecutorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterExecutorRequest) GetLabels() []*RegisterExecutorRequest_Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterExecutorRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type RegisterExecutorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterExecutorResponse) Reset() {
	*x = RegisterExecutorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExecutorResponse) ProtoMessage() {}

func (x *RegisterExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExecutorResponse.ProtoReflect.Descriptor instead.
func (*RegisterExecutorResponse) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{1}
}

type UnregisterExecutorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UnregisterExecutorRequest) Reset() {
	*x = UnregisterExecutorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterExecutorRequest) ProtoMessage() {}

func (x *UnregisterExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterExecutorRequest.ProtoReflect.Descriptor instead.
func (*UnregisterExecutorRequest) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterExecutorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnregisterExecutorRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnregisterExecutorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnregisterExecutorResponse) Reset() {
	*x = UnregisterExecutorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterExecutorResponse) ProtoMessage() {}

func (x *UnregisterExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterExecutorResponse.ProtoReflect.Descriptor instead.
func (*UnregisterExecutorResponse) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{3}
}

type ExecuteStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type    ExecuteStream_Type `protobuf:"varint,2,opt,name=type,proto3,enum=gotlin.ExecuteStream_Type" json:"type,omitempty"`
	Spent   int64              `protobuf:"varint,3,opt,name=spent,proto3" json:"spent,omitempty"`
	Timeout int64              `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Error   string             `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Op      *InstructionPb     `protobuf:"bytes,6,opt,name=op,proto3" json:"op,omitempty"`
	Args    []*InstructionPb   `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
	Result  *InstructionPb     `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ExecuteStream) Reset() {
	*x = ExecuteStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStream) ProtoMessage() {}

func (x *ExecuteStream) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStream.ProtoReflect.Descriptor instead.
func (*ExecuteStream) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteStream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecuteStream) GetType() ExecuteStream_Type {
	if x != nil {
		return x.Type
	}
	return ExecuteStream_Unknown
}

func (x *ExecuteStream) GetSpent() int64 {
	if x != nil {
		return x.Spent
	}
	return 0
}

func (x *ExecuteStream) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ExecuteStream) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteStream) GetOp() *InstructionPb {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *ExecuteStream) GetArgs() []*InstructionPb {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteStream) GetResult() *InstructionPb {
	if x != nil {
		return x.Result
	}
	return nil
}

type RequestSchedulerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dummy string `protobuf:"bytes,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
}

func (x *RequestSchedulerRequest) Reset() {
	*x = RequestSchedulerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSchedulerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSchedulerRequest) ProtoMessage() {}

func (x *RequestSchedulerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSchedulerRequest.ProtoReflect.Descriptor instead.
func (*RequestSchedulerRequest) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{5}
}

func (x *RequestSchedulerRequest) GetDummy() string {
	if x != nil {
		return x.Dummy
	}
	return ""
}

type RequestSchedulerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestSchedulerResponse) Reset() {
	*x = RequestSchedulerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSchedulerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSchedulerResponse) ProtoMessage() {}

func (x *RequestSchedulerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSchedulerResponse.ProtoReflect.Descriptor instead.
func (*RequestSchedulerResponse) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{6}
}

func (x *RequestSchedulerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProgramPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code      []byte `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Processor []byte `protobuf:"bytes,3,opt,name=processor,proto3" json:"processor,omitempty"`
}

func (x *ProgramPb) Reset() {
	*x = ProgramPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgramPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramPb) ProtoMessage() {}

func (x *ProgramPb) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramPb.ProtoReflect.Descriptor instead.
func (*ProgramPb) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{7}
}

func (x *ProgramPb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProgramPb) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *ProgramPb) GetProcessor() []byte {
	if x != nil {
		return x.Processor
	}
	return nil
}

type InstructionPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Id2     string `protobuf:"bytes,2,opt,name=id2,proto3" json:"id2,omitempty"`
	Opcode  string `protobuf:"bytes,3,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Operand []byte `protobuf:"bytes,4,opt,name=operand,proto3" json:"operand,omitempty"`
	Result  []byte `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *InstructionPb) Reset() {
	*x = InstructionPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstructionPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionPb) ProtoMessage() {}

func (x *InstructionPb) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionPb.ProtoReflect.Descriptor instead.
func (*InstructionPb) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{8}
}

func (x *InstructionPb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstructionPb) GetId2() string {
	if x != nil {
		return x.Id2
	}
	return ""
}

func (x *InstructionPb) GetOpcode() string {
	if x != nil {
		return x.Opcode
	}
	return ""
}

func (x *InstructionPb) GetOperand() []byte {
	if x != nil {
		return x.Operand
	}
	return nil
}

func (x *InstructionPb) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type RunProgramRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchedulerId  string           `protobuf:"bytes,1,opt,name=scheduler_id,json=schedulerId,proto3" json:"scheduler_id,omitempty"`
	Program      *ProgramPb       `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
	Instructions []*InstructionPb `protobuf:"bytes,3,rep,name=instructions,proto3" json:"instructions,omitempty"`
}

func (x *RunProgramRequest) Reset() {
	*x = RunProgramRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunProgramRequest) ProtoMessage() {}

func (x *RunProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunProgramRequest.ProtoReflect.Descriptor instead.
func (*RunProgramRequest) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{9}
}

func (x *RunProgramRequest) GetSchedulerId() string {
	if x != nil {
		return x.SchedulerId
	}
	return ""
}

func (x *RunProgramRequest) GetProgram() *ProgramPb {
	if x != nil {
		return x.Program
	}
	return nil
}

func (x *RunProgramRequest) GetInstructions() []*InstructionPb {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type RunProgramResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunProgramResponse) Reset() {
	*x = RunProgramResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunProgramResponse) ProtoMessage() {}

func (x *RunProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunProgramResponse.ProtoReflect.Descriptor instead.
func (*RunProgramResponse) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{10}
}

type WaitResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *WaitResultRequest) Reset() {
	*x = WaitResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResultRequest) ProtoMessage() {}

func (x *WaitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResultRequest.ProtoReflect.Descriptor instead.
func (*WaitResultRequest) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{11}
}

func (x *WaitResultRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type WaitResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result []byte `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *WaitResultResponse) Reset() {
	*x = WaitResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResultResponse) ProtoMessage() {}

func (x *WaitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResultResponse.ProtoReflect.Descriptor instead.
func (*WaitResultResponse) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{12}
}

func (x *WaitResultResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WaitResultResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WaitResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterExecutorRequest_Label struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RegisterExecutorRequest_Label) Reset() {
	*x = RegisterExecutorRequest_Label{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterExecutorRequest_Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExecutorRequest_Label) ProtoMessage() {}

func (x *RegisterExecutorRequest_Label) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExecutorRequest_Label.ProtoReflect.Descriptor instead.
func (*RegisterExecutorRequest_Label) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RegisterExecutorRequest_Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RegisterExecutorRequest_Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_gotlin_proto protoreflect.FileDescriptor

var file_gotlin_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x22, 0xad, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x3d, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x1a, 0x2f, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x41, 0x0a, 0x19, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x1c, 0x0a, 0x1a, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0xd1, 0x02, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x02, 0x6f,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e,
	0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x62, 0x52, 0x02,
	0x6f, 0x70, 0x12, 0x29, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x62, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x2d, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x62, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x39, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x10, 0x03, 0x22, 0x2f, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x22, 0x2a, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x50,
	0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x22, 0x7b, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x64, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x9e, 0x01, 0x0a, 0x11, 0x52, 0x75, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x74,
	0x6c, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x50, 0x62, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x39, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67,
	0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x62, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x75, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x11, 0x57, 0x61, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x52,
	0x0a, 0x12, 0x57, 0x61, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0xef, 0x03, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69,
	0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x6f, 0x74, 0x6c,
	0x69, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a,
	0x12, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x55, 0x6e, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e,
	0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x07,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x15,
	0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x57, 0x0a, 0x10, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x12, 0x19, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x57,
	0x61, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x2e, 0x67, 0x6f, 0x74, 0x6c,
	0x69, 0x6e, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x57, 0x61,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6f, 0x67, 0x75, 0x61, 0x69, 0x73, 0x2f, 0x67, 0x6f, 0x74, 0x6c,
	0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gotlin_proto_rawDescOnce sync.Once
	file_gotlin_proto_rawDescData = file_gotlin_proto_rawDesc
)

func file_gotlin_proto_rawDescGZIP() []byte {
	file_gotlin_proto_rawDescOnce.Do(func() {
		file_gotlin_proto_rawDescData = protoimpl.X.CompressGZIP(file_gotlin_proto_rawDescData)
	})
	return file_gotlin_proto_rawDescData
}

var file_gotlin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gotlin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gotlin_proto_goTypes = []interface{}{
	(ExecuteStream_Type)(0),               // 0: gotlin.ExecuteStream.Type
	(*RegisterExecutorRequest)(nil),       // 1: gotlin.RegisterExecutorRequest
	(*RegisterExecutorResponse)(nil),      // 2: gotlin.RegisterExecutorResponse
	(*UnregisterExecutorRequest)(nil),     // 3: gotlin.UnregisterExecutorRequest
	(*UnregisterExecutorResponse)(nil),    // 4: gotlin.UnregisterExecutorResponse
	(*ExecuteStream)(nil),                 // 5: gotlin.ExecuteStream
	(*RequestSchedulerRequest)(nil),       // 6: gotlin.RequestSchedulerRequest
	(*RequestSchedulerResponse)(nil),      // 7: gotlin.RequestSchedulerResponse
	(*ProgramPb)(nil),                     // 8: gotlin.ProgramPb
	(*InstructionPb)(nil),                 // 9: gotlin.InstructionPb
	(*RunProgramRequest)(nil),             // 10: gotlin.RunProgramRequest
	(*RunProgramResponse)(nil),            // 11: gotlin.RunProgramResponse
	(*WaitResultRequest)(nil),             // 12: gotlin.WaitResultRequest
	(*WaitResultResponse)(nil),            // 13: gotlin.WaitResultResponse
	(*RegisterExecutorRequest_Label)(nil), // 14: gotlin.RegisterExecutorRequest.Label
}
var file_gotlin_proto_depIdxs = []int32{
	14, // 0: gotlin.RegisterExecutorRequest.labels:type_name -> gotlin.RegisterExecutorRequest.Label
	0,  // 1: gotlin.ExecuteStream.type:type_name -> gotlin.ExecuteStream.Type
	9,  // 2: gotlin.ExecuteStream.op:type_name -> gotlin.InstructionPb
	9,  // 3: gotlin.ExecuteStream.args:type_name -> gotlin.InstructionPb
	9,  // 4: gotlin.ExecuteStream.result:type_name -> gotlin.InstructionPb
	8,  // 5: gotlin.RunProgramRequest.program:type_name -> gotlin.ProgramPb
	9,  // 6: gotlin.RunProgramRequest.instructions:type_name -> gotlin.InstructionPb
	1,  // 7: gotlin.ServerService.RegisterExecutor:input_type -> gotlin.RegisterExecutorRequest
	3,  // 8: gotlin.ServerService.UnregisterExecutor:input_type -> gotlin.UnregisterExecutorRequest
	5,  // 9: gotlin.ServerService.Execute:input_type -> gotlin.ExecuteStream
	6,  // 10: gotlin.ServerService.RequestScheduler:input_type -> gotlin.RequestSchedulerRequest
	10, // 11: gotlin.ServerService.RunProgram:input_type -> gotlin.RunProgramRequest
	12, // 12: gotlin.ServerService.WaitResult:input_type -> gotlin.WaitResultRequest
	2,  // 13: gotlin.ServerService.RegisterExecutor:output_type -> gotlin.RegisterExecutorResponse
	4,  // 14: gotlin.ServerService.UnregisterExecutor:output_type -> gotlin.UnregisterExecutorResponse
	5,  // 15: gotlin.ServerService.Execute:output_type -> gotlin.ExecuteStream
	7,  // 16: gotlin.ServerService.RequestScheduler:output_type -> gotlin.RequestSchedulerResponse
	11, // 17: gotlin.ServerService.RunProgram:output_type -> gotlin.RunProgramResponse
	13, // 18: gotlin.ServerService.WaitResult:output_type -> gotlin.WaitResultResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_gotlin_proto_init() }
func file_gotlin_proto_init() {
	if File_gotlin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gotlin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterExecutorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterExecutorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterExecutorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterExecutorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSchedulerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSchedulerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgramPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstructionPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunProgramRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunProgramResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterExecutorRequest_Label); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gotlin_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gotlin_proto_goTypes,
		DependencyIndexes: file_gotlin_proto_depIdxs,
		EnumInfos:         file_gotlin_proto_enumTypes,
		MessageInfos:      file_gotlin_proto_msgTypes,
	}.Build()
	File_gotlin_proto = out.File
	file_gotlin_proto_rawDesc = nil
	file_gotlin_proto_goTypes = nil
	file_gotlin_proto_depIdxs = nil
}
