// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gotlin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerServiceClient is the client API for ServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerServiceClient interface {
	RegisterExecutor(ctx context.Context, in *RegisterExecutorRequest, opts ...grpc.CallOption) (*RegisterExecutorResponse, error)
	UnregisterExecutor(ctx context.Context, in *UnregisterExecutorRequest, opts ...grpc.CallOption) (*UnregisterExecutorResponse, error)
	Execute(ctx context.Context, opts ...grpc.CallOption) (ServerService_ExecuteClient, error)
	RequestScheduler(ctx context.Context, in *RequestSchedulerRequest, opts ...grpc.CallOption) (*RequestSchedulerResponse, error)
	RunProgram(ctx context.Context, in *RunProgramRequest, opts ...grpc.CallOption) (*RunProgramResponse, error)
	WaitResult(ctx context.Context, in *WaitResultRequest, opts ...grpc.CallOption) (ServerService_WaitResultClient, error)
}

type serverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServerServiceClient(cc grpc.ClientConnInterface) ServerServiceClient {
	return &serverServiceClient{cc}
}

func (c *serverServiceClient) RegisterExecutor(ctx context.Context, in *RegisterExecutorRequest, opts ...grpc.CallOption) (*RegisterExecutorResponse, error) {
	out := new(RegisterExecutorResponse)
	err := c.cc.Invoke(ctx, "/gotlin.ServerService/RegisterExecutor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) UnregisterExecutor(ctx context.Context, in *UnregisterExecutorRequest, opts ...grpc.CallOption) (*UnregisterExecutorResponse, error) {
	out := new(UnregisterExecutorResponse)
	err := c.cc.Invoke(ctx, "/gotlin.ServerService/UnregisterExecutor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) Execute(ctx context.Context, opts ...grpc.CallOption) (ServerService_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServerService_ServiceDesc.Streams[0], "/gotlin.ServerService/Execute", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverServiceExecuteClient{stream}
	return x, nil
}

type ServerService_ExecuteClient interface {
	Send(*ExecuteStream) error
	Recv() (*ExecuteStream, error)
	grpc.ClientStream
}

type serverServiceExecuteClient struct {
	grpc.ClientStream
}

func (x *serverServiceExecuteClient) Send(m *ExecuteStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serverServiceExecuteClient) Recv() (*ExecuteStream, error) {
	m := new(ExecuteStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverServiceClient) RequestScheduler(ctx context.Context, in *RequestSchedulerRequest, opts ...grpc.CallOption) (*RequestSchedulerResponse, error) {
	out := new(RequestSchedulerResponse)
	err := c.cc.Invoke(ctx, "/gotlin.ServerService/RequestScheduler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) RunProgram(ctx context.Context, in *RunProgramRequest, opts ...grpc.CallOption) (*RunProgramResponse, error) {
	out := new(RunProgramResponse)
	err := c.cc.Invoke(ctx, "/gotlin.ServerService/RunProgram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) WaitResult(ctx context.Context, in *WaitResultRequest, opts ...grpc.CallOption) (ServerService_WaitResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServerService_ServiceDesc.Streams[1], "/gotlin.ServerService/WaitResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverServiceWaitResultClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerService_WaitResultClient interface {
	Recv() (*WaitResultResponse, error)
	grpc.ClientStream
}

type serverServiceWaitResultClient struct {
	grpc.ClientStream
}

func (x *serverServiceWaitResultClient) Recv() (*WaitResultResponse, error) {
	m := new(WaitResultResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServerServiceServer is the server API for ServerService service.
// All implementations must embed UnimplementedServerServiceServer
// for forward compatibility
type ServerServiceServer interface {
	RegisterExecutor(context.Context, *RegisterExecutorRequest) (*RegisterExecutorResponse, error)
	UnregisterExecutor(context.Context, *UnregisterExecutorRequest) (*UnregisterExecutorResponse, error)
	Execute(ServerService_ExecuteServer) error
	RequestScheduler(context.Context, *RequestSchedulerRequest) (*RequestSchedulerResponse, error)
	RunProgram(context.Context, *RunProgramRequest) (*RunProgramResponse, error)
	WaitResult(*WaitResultRequest, ServerService_WaitResultServer) error
	mustEmbedUnimplementedServerServiceServer()
}

// UnimplementedServerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServerServiceServer struct {
}

func (UnimplementedServerServiceServer) RegisterExecutor(context.Context, *RegisterExecutorRequest) (*RegisterExecutorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterExecutor not implemented")
}
func (UnimplementedServerServiceServer) UnregisterExecutor(context.Context, *UnregisterExecutorRequest) (*UnregisterExecutorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterExecutor not implemented")
}
func (UnimplementedServerServiceServer) Execute(ServerService_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedServerServiceServer) RequestScheduler(context.Context, *RequestSchedulerRequest) (*RequestSchedulerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestScheduler not implemented")
}
func (UnimplementedServerServiceServer) RunProgram(context.Context, *RunProgramRequest) (*RunProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunProgram not implemented")
}
func (UnimplementedServerServiceServer) WaitResult(*WaitResultRequest, ServerService_WaitResultServer) error {
	return status.Errorf(codes.Unimplemented, "method WaitResult not implemented")
}
func (UnimplementedServerServiceServer) mustEmbedUnimplementedServerServiceServer() {}

// UnsafeServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServiceServer will
// result in compilation errors.
type UnsafeServerServiceServer interface {
	mustEmbedUnimplementedServerServiceServer()
}

func RegisterServerServiceServer(s grpc.ServiceRegistrar, srv ServerServiceServer) {
	s.RegisterService(&ServerService_ServiceDesc, srv)
}

func _ServerService_RegisterExecutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterExecutorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).RegisterExecutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotlin.ServerService/RegisterExecutor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).RegisterExecutor(ctx, req.(*RegisterExecutorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_UnregisterExecutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterExecutorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).UnregisterExecutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotlin.ServerService/UnregisterExecutor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).UnregisterExecutor(ctx, req.(*UnregisterExecutorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServerServiceServer).Execute(&serverServiceExecuteServer{stream})
}

type ServerService_ExecuteServer interface {
	Send(*ExecuteStream) error
	Recv() (*ExecuteStream, error)
	grpc.ServerStream
}

type serverServiceExecuteServer struct {
	grpc.ServerStream
}

func (x *serverServiceExecuteServer) Send(m *ExecuteStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serverServiceExecuteServer) Recv() (*ExecuteStream, error) {
	m := new(ExecuteStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ServerService_RequestScheduler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSchedulerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).RequestScheduler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotlin.ServerService/RequestScheduler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).RequestScheduler(ctx, req.(*RequestSchedulerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_RunProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).RunProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotlin.ServerService/RunProgram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).RunProgram(ctx, req.(*RunProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_WaitResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WaitResultRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerServiceServer).WaitResult(m, &serverServiceWaitResultServer{stream})
}

type ServerService_WaitResultServer interface {
	Send(*WaitResultResponse) error
	grpc.ServerStream
}

type serverServiceWaitResultServer struct {
	grpc.ServerStream
}

func (x *serverServiceWaitResultServer) Send(m *WaitResultResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ServerService_ServiceDesc is the grpc.ServiceDesc for ServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gotlin.ServerService",
	HandlerType: (*ServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterExecutor",
			Handler:    _ServerService_RegisterExecutor_Handler,
		},
		{
			MethodName: "UnregisterExecutor",
			Handler:    _ServerService_UnregisterExecutor_Handler,
		},
		{
			MethodName: "RequestScheduler",
			Handler:    _ServerService_RequestScheduler_Handler,
		},
		{
			MethodName: "RunProgram",
			Handler:    _ServerService_RunProgram_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _ServerService_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WaitResult",
			Handler:       _ServerService_WaitResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gotlin.proto",
}
