// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: gotlin.proto

package gotlin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_Unknown            CommandType = 0
	CommandType_ConnectToServer    CommandType = 1
	CommandType_Ping               CommandType = 2
	CommandType_Pong               CommandType = 3
	CommandType_ExecuteInstruction CommandType = 4
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "Unknown",
		1: "ConnectToServer",
		2: "Ping",
		3: "Pong",
		4: "ExecuteInstruction",
	}
	CommandType_value = map[string]int32{
		"Unknown":            0,
		"ConnectToServer":    1,
		"Ping":               2,
		"Pong":               3,
		"ExecuteInstruction": 4,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_gotlin_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_gotlin_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{0}
}

type RegisterExecutorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Labels []*RegisterExecutorRequest_Label `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Host   string                           `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *RegisterExecutorRequest) Reset() {
	*x = RegisterExecutorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExecutorRequest) ProtoMessage() {}

func (x *RegisterExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExecutorRequest.ProtoReflect.Descriptor instead.
func (*RegisterExecutorRequest) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterExecutorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterExecutorRequest) GetLabels() []*RegisterExecutorRequest_Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterExecutorRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type RegisterExecutorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterExecutorResponse) Reset() {
	*x = RegisterExecutorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExecutorResponse) ProtoMessage() {}

func (x *RegisterExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExecutorResponse.ProtoReflect.Descriptor instead.
func (*RegisterExecutorResponse) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{1}
}

type UnregisterExecutorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UnregisterExecutorRequest) Reset() {
	*x = UnregisterExecutorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterExecutorRequest) ProtoMessage() {}

func (x *UnregisterExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterExecutorRequest.ProtoReflect.Descriptor instead.
func (*UnregisterExecutorRequest) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterExecutorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnregisterExecutorRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnregisterExecutorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnregisterExecutorResponse) Reset() {
	*x = UnregisterExecutorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterExecutorResponse) ProtoMessage() {}

func (x *UnregisterExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterExecutorResponse.ProtoReflect.Descriptor instead.
func (*UnregisterExecutorResponse) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{3}
}

type CommandFromClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string                                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type               CommandType                           `protobuf:"varint,2,opt,name=type,proto3,enum=gotlin.CommandType" json:"type,omitempty"`
	Spent              int64                                 `protobuf:"varint,3,opt,name=spent,proto3" json:"spent,omitempty"`
	ExecuteInstruction *CommandFromClient_ExecuteInstruction `protobuf:"bytes,4,opt,name=execute_instruction,json=executeInstruction,proto3" json:"execute_instruction,omitempty"`
}

func (x *CommandFromClient) Reset() {
	*x = CommandFromClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandFromClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandFromClient) ProtoMessage() {}

func (x *CommandFromClient) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandFromClient.ProtoReflect.Descriptor instead.
func (*CommandFromClient) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{4}
}

func (x *CommandFromClient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandFromClient) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_Unknown
}

func (x *CommandFromClient) GetSpent() int64 {
	if x != nil {
		return x.Spent
	}
	return 0
}

func (x *CommandFromClient) GetExecuteInstruction() *CommandFromClient_ExecuteInstruction {
	if x != nil {
		return x.ExecuteInstruction
	}
	return nil
}

type CommandToClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type               CommandType                         `protobuf:"varint,2,opt,name=type,proto3,enum=gotlin.CommandType" json:"type,omitempty"`
	Timeout            int64                               `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Error              string                              `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ExecuteInstruction *CommandToClient_ExecuteInstruction `protobuf:"bytes,5,opt,name=execute_instruction,json=executeInstruction,proto3" json:"execute_instruction,omitempty"`
}

func (x *CommandToClient) Reset() {
	*x = CommandToClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandToClient) ProtoMessage() {}

func (x *CommandToClient) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandToClient.ProtoReflect.Descriptor instead.
func (*CommandToClient) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{5}
}

func (x *CommandToClient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandToClient) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_Unknown
}

func (x *CommandToClient) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CommandToClient) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandToClient) GetExecuteInstruction() *CommandToClient_ExecuteInstruction {
	if x != nil {
		return x.ExecuteInstruction
	}
	return nil
}

type RegisterExecutorRequest_Label struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RegisterExecutorRequest_Label) Reset() {
	*x = RegisterExecutorRequest_Label{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterExecutorRequest_Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExecutorRequest_Label) ProtoMessage() {}

func (x *RegisterExecutorRequest_Label) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExecutorRequest_Label.ProtoReflect.Descriptor instead.
func (*RegisterExecutorRequest_Label) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RegisterExecutorRequest_Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RegisterExecutorRequest_Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CommandFromClient_ExecuteInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Opcode string `protobuf:"bytes,2,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Result []byte `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CommandFromClient_ExecuteInstruction) Reset() {
	*x = CommandFromClient_ExecuteInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandFromClient_ExecuteInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandFromClient_ExecuteInstruction) ProtoMessage() {}

func (x *CommandFromClient_ExecuteInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandFromClient_ExecuteInstruction.ProtoReflect.Descriptor instead.
func (*CommandFromClient_ExecuteInstruction) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CommandFromClient_ExecuteInstruction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandFromClient_ExecuteInstruction) GetOpcode() string {
	if x != nil {
		return x.Opcode
	}
	return ""
}

func (x *CommandFromClient_ExecuteInstruction) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type CommandToClient_Instruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Opcode  string `protobuf:"bytes,2,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Operand []byte `protobuf:"bytes,3,opt,name=operand,proto3" json:"operand,omitempty"`
	Result  []byte `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CommandToClient_Instruction) Reset() {
	*x = CommandToClient_Instruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandToClient_Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandToClient_Instruction) ProtoMessage() {}

func (x *CommandToClient_Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandToClient_Instruction.ProtoReflect.Descriptor instead.
func (*CommandToClient_Instruction) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CommandToClient_Instruction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandToClient_Instruction) GetOpcode() string {
	if x != nil {
		return x.Opcode
	}
	return ""
}

func (x *CommandToClient_Instruction) GetOperand() []byte {
	if x != nil {
		return x.Operand
	}
	return nil
}

func (x *CommandToClient_Instruction) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type CommandToClient_ExecuteInstruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   *CommandToClient_Instruction   `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Args []*CommandToClient_Instruction `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *CommandToClient_ExecuteInstruction) Reset() {
	*x = CommandToClient_ExecuteInstruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gotlin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandToClient_ExecuteInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandToClient_ExecuteInstruction) ProtoMessage() {}

func (x *CommandToClient_ExecuteInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_gotlin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandToClient_ExecuteInstruction.ProtoReflect.Descriptor instead.
func (*CommandToClient_ExecuteInstruction) Descriptor() ([]byte, []int) {
	return file_gotlin_proto_rawDescGZIP(), []int{5, 1}
}

func (x *CommandToClient_ExecuteInstruction) GetOp() *CommandToClient_Instruction {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *CommandToClient_ExecuteInstruction) GetArgs() []*CommandToClient_Instruction {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_gotlin_proto protoreflect.FileDescriptor

var file_gotlin_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x22, 0xad, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x3d, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x1a, 0x2f, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x41, 0x0a, 0x19, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x1c, 0x0a, 0x1a, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x97, 0x02, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x46,
	0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x13, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x12, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x54, 0x0a, 0x12, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xc5, 0x03,
	0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x5b, 0x0a, 0x13, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x12, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x67, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x1a, 0x82, 0x01, 0x0a, 0x12, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x37, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x6f, 0x74,
	0x6c, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x2a, 0x5b, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x10, 0x04, 0x32, 0x93, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69,
	0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x6f, 0x74, 0x6c,
	0x69, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a,
	0x12, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x55, 0x6e, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e,
	0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x19,
	0x2e, 0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x46,
	0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x6f, 0x74, 0x6c,
	0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6f, 0x67, 0x75, 0x61, 0x69, 0x73, 0x2f,
	0x67, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gotlin_proto_rawDescOnce sync.Once
	file_gotlin_proto_rawDescData = file_gotlin_proto_rawDesc
)

func file_gotlin_proto_rawDescGZIP() []byte {
	file_gotlin_proto_rawDescOnce.Do(func() {
		file_gotlin_proto_rawDescData = protoimpl.X.CompressGZIP(file_gotlin_proto_rawDescData)
	})
	return file_gotlin_proto_rawDescData
}

var file_gotlin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gotlin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gotlin_proto_goTypes = []interface{}{
	(CommandType)(0),                             // 0: gotlin.CommandType
	(*RegisterExecutorRequest)(nil),              // 1: gotlin.RegisterExecutorRequest
	(*RegisterExecutorResponse)(nil),             // 2: gotlin.RegisterExecutorResponse
	(*UnregisterExecutorRequest)(nil),            // 3: gotlin.UnregisterExecutorRequest
	(*UnregisterExecutorResponse)(nil),           // 4: gotlin.UnregisterExecutorResponse
	(*CommandFromClient)(nil),                    // 5: gotlin.CommandFromClient
	(*CommandToClient)(nil),                      // 6: gotlin.CommandToClient
	(*RegisterExecutorRequest_Label)(nil),        // 7: gotlin.RegisterExecutorRequest.Label
	(*CommandFromClient_ExecuteInstruction)(nil), // 8: gotlin.CommandFromClient.ExecuteInstruction
	(*CommandToClient_Instruction)(nil),          // 9: gotlin.CommandToClient.Instruction
	(*CommandToClient_ExecuteInstruction)(nil),   // 10: gotlin.CommandToClient.ExecuteInstruction
}
var file_gotlin_proto_depIdxs = []int32{
	7,  // 0: gotlin.RegisterExecutorRequest.labels:type_name -> gotlin.RegisterExecutorRequest.Label
	0,  // 1: gotlin.CommandFromClient.type:type_name -> gotlin.CommandType
	8,  // 2: gotlin.CommandFromClient.execute_instruction:type_name -> gotlin.CommandFromClient.ExecuteInstruction
	0,  // 3: gotlin.CommandToClient.type:type_name -> gotlin.CommandType
	10, // 4: gotlin.CommandToClient.execute_instruction:type_name -> gotlin.CommandToClient.ExecuteInstruction
	9,  // 5: gotlin.CommandToClient.ExecuteInstruction.op:type_name -> gotlin.CommandToClient.Instruction
	9,  // 6: gotlin.CommandToClient.ExecuteInstruction.args:type_name -> gotlin.CommandToClient.Instruction
	1,  // 7: gotlin.ServerService.RegisterExecutor:input_type -> gotlin.RegisterExecutorRequest
	3,  // 8: gotlin.ServerService.UnregisterExecutor:input_type -> gotlin.UnregisterExecutorRequest
	5,  // 9: gotlin.ServerService.ExecuteCommand:input_type -> gotlin.CommandFromClient
	2,  // 10: gotlin.ServerService.RegisterExecutor:output_type -> gotlin.RegisterExecutorResponse
	4,  // 11: gotlin.ServerService.UnregisterExecutor:output_type -> gotlin.UnregisterExecutorResponse
	6,  // 12: gotlin.ServerService.ExecuteCommand:output_type -> gotlin.CommandToClient
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_gotlin_proto_init() }
func file_gotlin_proto_init() {
	if File_gotlin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gotlin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterExecutorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterExecutorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterExecutorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterExecutorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandFromClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandToClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterExecutorRequest_Label); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandFromClient_ExecuteInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandToClient_Instruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gotlin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandToClient_ExecuteInstruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gotlin_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gotlin_proto_goTypes,
		DependencyIndexes: file_gotlin_proto_depIdxs,
		EnumInfos:         file_gotlin_proto_enumTypes,
		MessageInfos:      file_gotlin_proto_msgTypes,
	}.Build()
	File_gotlin_proto = out.File
	file_gotlin_proto_rawDesc = nil
	file_gotlin_proto_goTypes = nil
	file_gotlin_proto_depIdxs = nil
}
