{
 "title": "Gotlin Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Service Up At",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gotlin_server_up_timestamp)"
    }
   ]
  },
  {
   "title": "Running Executors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(gotlin_executor_running)" }
   ]
  },
  {
   "title": "Time to Execute Fail",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gotlin_executor_execution_time_total{error=\"1\"})"
    }
   ]
  },
  {
   "title": "Running Programs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(gotlin_program_running)" }
   ]
  },
  {
   "title": "Error Programs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gotlin_program_executed_error_total"
    }
   ]
  },
  {
   "title": "Submitted Programs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gotlin_program_submitted_total" }
   ]
  },
  {
   "title": "Executors Execute Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(gotlin_executor_execution_time_total{error=\"0\"}) by (host)",
     "legendFormat": "executor-{{host}}"
    }
   ]
  },
  {
   "title": "OpCodes Execute Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(gotlin_instruction_opcode_execution_number_total{error=\"0\"}) by (opcode)",
     "legendFormat": "{{opcode}}"
    }
   ]
  },
  {
   "title": "Submitted Programs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gotlin_program_submitted_total)",
     "legendFormat": "numbers"
    }
   ]
  },
  {
   "title": "Submitted Instructions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gotlin_instruction_opcode_execution_time_total)",
     "legendFormat": "numbers"
    }
   ]
  }
 ]
}