name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: test
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: gotlin
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Run coverage
        run: go test -bench=. -coverprofile=coverage.txt -covermode=atomic -v
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
